_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
algorithm:
    value: kmeans
dbscan_params:
    value: null
experiment_name:
    value: kmeans_basic_5clusters
feature_set:
    value:
        - avg_ROA
        - avg_ROE
        - avg_OperatingMargin
        - avg_log_Revenue
        - avg_log_Assets
hierarchical_params:
    value: null
kmeans_params:
    value:
        max_iter: 300
n_clusters:
    value: 5
random_seed:
    value: 42
scaler:
    value: standard
